Player:
  walk_step: 0.24    # detik. waktu untuk lewat satu tile
  run_step: 0.12     # -- waktu lewat pas lari --
  walk_noise_rad: 3  # tile. radius noise yang dihasilkan walk
  run_noise_rad: 7   # -- radius noise lari --
  noise_spacing: 0.7 # detik. jeda waktu sampai bisa buat noise lagi

Director:
  sigma:  
    # standar deviasi distribusi gaussian untuk acak seberapa melesetnya clue director
    # serta bagaimana laju persebarannya terhadap tile sekitar
    walk: 5.5
    run: 4.0
  cooldown: # jeda waktu sampai clue dikasih lagi
    walk: 5.0
    run: 3.0

Alien:
  patrol_nodes: [[5, 2], [17, 2], [12, 7], [17, 9], [16, 17], [11, 13], [4, 17], [3, 9]]  # keliling titik-titik ini selama tidak ada clue
  vision: 7                 # tile. jarak pandang (360 derajat)
  sight_timeout: 2.5        # detik. vision kehalang selama itu, keluar dari state hunt
  investigate_timeout: 8.0  # detik. lama investigasi di sekitar clue

  diffuse_rate: 0.30  # porsi belief yang menyebar ke walkable tile sekitar untuk prediksi posisi player selanjutnya
  outlier: 0.02       # batas bawah (minimal) kemungkinan mengunjungi tile agar tidak ada yang kemungkinannya < 0 dan tidak akan dikunjungi
  miss: 0.03          # kemungkinan tidak melihat player padahal dalam jangkauan vision. P(tidak lihat player | player visible terhadap alien)
  dist_penalty: 0.08  # faktor penalty untuk kemungkinan memilih tile yang lebih jauh walaupun probabilitas hadirnya playernya tinggi

  step_time:  # detik. waktu untuk lewat satu tile di tiap mode
    PATROL: 0.45
    INVESTIGATE: 0.26
    HUNT: 0.14

Generator:
  radius: 10      # tile. radius noise generator
  cooldown: 10.0  # detik. jedak waktu sampai bisa dinyalakan lagi

World:
  cell_size: 40 # pixel. satu tile luasnya cell_size * cell_size
  move_dir: [[1, 0], [-1, 0], [0, 1], [0, -1]] # arah gerak
  map: [ 
    # Bisa dimodifikasi.
    # -- Tapi bentuknya harus kotak! --
    "#############################", # tiap simbol mewakili satu tile world
    "#P....#.....o...............#", # N: noise generator (selanjutnya disebut 'generator' aja)
    "#.....#.....................#", # o: obstacle. membatasi langkah saja
    "#..oo.....###..N............#", # #: wall. membatasi langkah dan vision
    "#..oo.....#.................#",
    "#.........#..oo.............#",
    "####.######.###.#############",
    "#........#..................#",
    "#..N.....#...oo.............#",
    "#........#..................#",
    "#..###......###.............#",
    "#..#..........#.............#",
    "#.....oo.......o............#",
    "#...........#...............#",
    "######.####.#################",
    "#........#.....A...........E#",
    "#..oo....#...N..............#",
    "#........#..................#",
    "#..N.........o..............#",
    "#############################",
  ]