Player:
  walk_step: 0.24
  walk_noise_rad: 3
  run_step: 0.12
  run_noise_rad: 7
  noise_spacing: 0.7

Director:

Alien:

Generator:
  radius: 20
  cooldown: 10.0

World:
  cell_size: 40
  move_dir: [[1, 0], [-1, 0], [0, 1], [0, -1]]
  map: [ 
    "#############################", # N: noise generator (selanjutnya disebut 'generator' aja) 
    "#P....#.....o...............#", # o: obstacle. membatasi langkah saja
    "#.....#.....................#", # #: wall. membatasi langkah dan vision
    "#..oo.....###..N............#",
    "#..oo.....#.................#",
    "#.........#..oo.............#",
    "####.######.###.#############",
    "#........#..................#",
    "#..N.....#...oo.............#",
    "#........#..................#",
    "#..###......###.............#",
    "#..#..........#.............#",
    "#.....oo.......o............#",
    "#...........#...............#",
    "######.####.#################",
    "#........#.....A...........E#",
    "#..oo....#...N..............#",
    "#........#..................#",
    "#..N.........o..............#",
    "#############################",
  ]